// THIS FILE IS AUTOMATICALLY GENERATED by https://github.com/swift-aws/aws-sdk-swift/blob/master/CodeGenerator/Sources/CodeGenerator/main.swift. DO NOT EDIT.

import AWSSDKSwiftCore

/// Error enum for ApplicationAutoScaling
public enum ApplicationAutoScalingErrorType: AWSErrorType {
    case concurrentUpdateException(message: String?)
    case failedResourceAccessException(message: String?)
    case internalServiceException(message: String?)
    case invalidNextTokenException(message: String?)
    case limitExceededException(message: String?)
    case objectNotFoundException(message: String?)
    case validationException(message: String?)
}

extension ApplicationAutoScalingErrorType {
    public init?(errorCode: String, message: String?){
        var errorCode = errorCode
        if let index = errorCode.firstIndex(of: "#") {
            errorCode = String(errorCode[errorCode.index(index, offsetBy: 1)...])
        }
        switch errorCode {
        case "ConcurrentUpdateException":
            self = .concurrentUpdateException(message: message)
        case "FailedResourceAccessException":
            self = .failedResourceAccessException(message: message)
        case "InternalServiceException":
            self = .internalServiceException(message: message)
        case "InvalidNextTokenException":
            self = .invalidNextTokenException(message: message)
        case "LimitExceededException":
            self = .limitExceededException(message: message)
        case "ObjectNotFoundException":
            self = .objectNotFoundException(message: message)
        case "ValidationException":
            self = .validationException(message: message)
        default:
            return nil
        }
    }
}

extension ApplicationAutoScalingErrorType : CustomStringConvertible {
    public var description : String {
        switch self {
        case .concurrentUpdateException(let message):
            return "ConcurrentUpdateException: \(message ?? "")"
        case .failedResourceAccessException(let message):
            return "FailedResourceAccessException: \(message ?? "")"
        case .internalServiceException(let message):
            return "InternalServiceException: \(message ?? "")"
        case .invalidNextTokenException(let message):
            return "InvalidNextTokenException: \(message ?? "")"
        case .limitExceededException(let message):
            return "LimitExceededException: \(message ?? "")"
        case .objectNotFoundException(let message):
            return "ObjectNotFoundException: \(message ?? "")"
        case .validationException(let message):
            return "ValidationException: \(message ?? "")"
        }
    }
}
